### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by Adam-Meza** [The-Never-Ending-Story/front-end#40]

**Comment by sdmisra** [comment]
This one is in progress - current branch is refactor/welcomepage-framer.

Comments within files to give more context / next steps as we pass it back and forth

Spec:
<img width="416" alt="Screenshot 2023-08-18 at 11 50 19 AM" src="https://github.com/The-Never-Ending-Story/front-end/assets/117242156/0781ff11-e40a-4891-ac53-01a2bfd97ccb">
